services:
  mysql:
    image: mysql:8.0
    container_name: mysql-papeleria
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-papeleria}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - papeleria-net


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: papeleria-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-}
    depends_on:
      - mysql
    networks:
      - papeleria-net

volumes:
  mysql_data:

networks:
  papeleria-net:
